# Generated by Django 5.0.6 on 2025-06-29 07:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARVRTrainingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('arvr_file', models.FileField(blank=True, null=True, upload_to='arvr_files/')),
            ],
        ),
        migrations.CreateModel(
            name='BiometricAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField(verbose_name='Sr.No.')),
                ('pay_code', models.CharField(max_length=20, verbose_name='PayCode')),
                ('card_no', models.CharField(max_length=20, verbose_name='Card No')),
                ('employee_name', models.CharField(max_length=100, verbose_name='Employee Name')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('designation', models.CharField(max_length=100, verbose_name='Designation')),
                ('shift', models.CharField(max_length=10, verbose_name='Shift')),
                ('start', models.TimeField(verbose_name='Start')),
                ('in_time', models.TimeField(verbose_name='In')),
                ('out_time', models.TimeField(verbose_name='Out')),
                ('hrs_works', models.TimeField(blank=True, null=True, verbose_name='Hrs Works')),
                ('status', models.CharField(max_length=10, verbose_name='Status')),
                ('early_arrival', models.CharField(blank=True, max_length=100, null=True, verbose_name='Early Arriv.')),
                ('late_arrival', models.CharField(blank=True, max_length=100, null=True, verbose_name='Late Arriv.')),
                ('shift_early', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shift Early')),
                ('excess_lunch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Excess Lunch')),
                ('ot', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ot')),
                ('ot_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ot Amount')),
                ('manual', models.CharField(blank=True, max_length=100, null=True, verbose_name='Manual')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_code', models.CharField(max_length=20, unique=True)),
                ('card_no', models.CharField(max_length=20, unique=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('desig_category', models.CharField(blank=True, max_length=100, null=True)),
                ('joining_date', models.DateField()),
                ('auth_shift', models.CharField(max_length=50)),
                ('shift_type', models.CharField(max_length=50)),
                ('shift_pattern', models.CharField(max_length=50)),
                ('first_weekly_off', models.CharField(max_length=10)),
                ('second_weekly_off', models.CharField(blank=True, max_length=10, null=True)),
                ('second_weekly_off_fh', models.CharField(blank=True, max_length=10, null=True)),
                ('ot_allowed_rate', models.BooleanField(default=False)),
                ('round_the_clock', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('level_1', 'Level 1'), ('level_2', 'Level 2'), ('level_3', 'Level 3'), ('level_4', 'Level 4')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LevelThreeOJTDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LevelThreeProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Production', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LevelThreeQAOJTDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LevelThreeQATraineeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traineeId', models.CharField(max_length=100)),
                ('trainee_name', models.CharField(max_length=100)),
                ('trainer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LevelThreeQATrainingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.PositiveIntegerField()),
                ('topic', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LevelThreeQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='QualityLevelThree', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LevelThreeTrainingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.PositiveIntegerField()),
                ('topic', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LevelTwoLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LevelTwoOJTDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LevelTwoProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Production', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LevelTwoQAOJTDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LevelTwoQATraineeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traineeId', models.CharField(max_length=100)),
                ('trainee_name', models.CharField(max_length=100)),
                ('trainer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LevelTwoQATrainingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.PositiveIntegerField()),
                ('topic', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LevelTwoQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Quality', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LevelTwoTrainingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.PositiveIntegerField()),
                ('topic', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='machines/')),
                ('level', models.IntegerField()),
                ('process', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineAllocationTrackingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_number', models.IntegerField(unique=True)),
                ('skill', models.CharField(default='', max_length=100)),
                ('minimum_skill_required', models.CharField(max_length=100)),
                ('min_operator_required', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('employeeid', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('developer', 'Developer'), ('management', 'Management'), ('admin', 'Admin'), ('instructor', 'Instructor'), ('operator', 'Operator')], default='', max_length=20)),
                ('hq', models.CharField(blank=True, max_length=50, null=True)),
                ('factory', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='app1.factory')),
            ],
        ),
        migrations.AddField(
            model_name='factory',
            name='hq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factories', to='app1.hq'),
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='app1.level')),
            ],
        ),
        migrations.CreateModel(
            name='LevelThreeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_three_lines', to='app1.levelthreeproduction')),
            ],
        ),
        migrations.CreateModel(
            name='LevelThreeQAOJTScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.levelthreeqaojtday')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ojtscores', to='app1.levelthreeqatraineeinfo')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.levelthreeqatrainingtopic')),
            ],
        ),
        migrations.CreateModel(
            name='LevelThreeQualityLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualitylevelthreelines', to='app1.levelthreequality')),
            ],
        ),
        migrations.AddField(
            model_name='levelthreeqatraineeinfo',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levelthreequalitytrainees', to='app1.levelthreequalityline'),
        ),
        migrations.CreateModel(
            name='LevelThreeSubStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_three_substations', to='app1.levelthreeline')),
            ],
        ),
        migrations.CreateModel(
            name='LevelThreeTraineeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainee_Id', models.CharField(default='', max_length=100)),
                ('trainee_name', models.CharField(max_length=100)),
                ('trainer_name', models.CharField(max_length=100)),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levelthree_trainees', to='app1.levelthreeline')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levelthree_trainees', to='app1.levelthreesubstation')),
            ],
        ),
        migrations.CreateModel(
            name='LevelThreeOJTScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(10, 'OK'), (0, 'Not OK')])),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.levelthreeojtday')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ojtscores', to='app1.levelthreetraineeinfo')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.levelthreetrainingtopic')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLevelAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employeemaster')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.level')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.leveltwoline')),
            ],
        ),
        migrations.AddField(
            model_name='leveltwoline',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leveltwolines', to='app1.leveltwoproduction'),
        ),
        migrations.CreateModel(
            name='LevelTwoQAOJTScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.leveltwoqaojtday')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ojtscores', to='app1.leveltwoqatraineeinfo')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.leveltwoqatrainingtopic')),
            ],
        ),
        migrations.CreateModel(
            name='LevelTwoQualityLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualityleveltwolines', to='app1.leveltwoquality')),
            ],
        ),
        migrations.AddField(
            model_name='leveltwoqatraineeinfo',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualitytrainees', to='app1.leveltwoqualityline'),
        ),
        migrations.CreateModel(
            name='LevelTwoSubStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substations', to='app1.leveltwoline')),
            ],
        ),
        migrations.CreateModel(
            name='LevelTwoTraineeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traineeId', models.CharField(max_length=100)),
                ('trainee_name', models.CharField(max_length=100)),
                ('trainer_name', models.CharField(max_length=100)),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainees', to='app1.leveltwoline')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainees', to='app1.leveltwosubstation')),
            ],
        ),
        migrations.CreateModel(
            name='LevelTwoOJTScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(10, 'OK'), (0, 'Not OK')])),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.leveltwoojtday')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ojtscores', to='app1.leveltwotraineeinfo')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.leveltwotrainingtopic')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='app1.department')),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='app1.line'),
        ),
        migrations.CreateModel(
            name='MachineAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employeemaster')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.machine')),
            ],
        ),
        migrations.CreateModel(
            name='OperatorLevelEmailTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.level')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_level_trackings', to='app1.employeemaster')),
            ],
        ),
        migrations.CreateModel(
            name='OperatorLevelTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.level')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_trackings', to='app1.employeemaster')),
            ],
        ),
        migrations.CreateModel(
            name='SkillTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_trainings', to='app1.level')),
            ],
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='app1.days')),
                ('skill_training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='app1.skilltraining')),
            ],
        ),
        migrations.CreateModel(
            name='SubTopicContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopiccontents', to='app1.subtopic')),
            ],
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('subtopic_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcq_questions', to='app1.subtopiccontent')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='app1.operatorlevelemailtracking')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('training_file', models.FileField(blank=True, null=True, upload_to='training_files/')),
                ('url_link', models.URLField(blank=True, max_length=500, null=True)),
                ('subtopic_content', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='app1.subtopiccontent')),
            ],
        ),
        migrations.CreateModel(
            name='OperatorSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.CharField(max_length=100)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employeemaster')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.station')),
            ],
            options={
                'unique_together': {('operator', 'station')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.CharField(max_length=10)),
                ('month', models.DateField()),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employeemaster')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.station')),
            ],
            options={
                'unique_together': {('operator', 'station', 'month')},
            },
        ),
        migrations.CreateModel(
            name='OperatorTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employeemaster')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.trainingtopic')),
            ],
            options={
                'unique_together': {('operator', 'topic')},
            },
        ),
    ]
