# Generated by Django 5.1.1 on 2025-06-30 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('new_operators_joined', models.PositiveIntegerField(default=0)),
                ('new_operators_trained', models.PositiveIntegerField(default=0)),
                ('total_trainings_planned', models.PositiveIntegerField(default=0)),
                ('total_trainings_actual', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UnifiedDefectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('category', models.CharField(choices=[('MSIL', 'MSIL'), ('Tier-1', 'Tier-1'), ('All Plants', 'All Plants'), ('CTQ', 'CTQ')], max_length=30)),
                ('total_defects', models.PositiveIntegerField(default=0)),
                ('ctq_defects', models.PositiveIntegerField(default=0)),
                ('total_internal_rejection', models.PositiveIntegerField(default=0)),
                ('ctq_internal_rejection', models.PositiveIntegerField(default=0)),
                ('tier1_total_defects', models.PositiveIntegerField(default=0)),
                ('tier1_ctq_defects', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MultiSkilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('scheduled', 'Scheduled'), ('inprogress', 'In Progress'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('refreshment_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employeemaster')),
                ('skill_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.operatorskill')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.station')),
            ],
        ),
        migrations.CreateModel(
            name='RefreshmentTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason_for_refreshment', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employeemaster')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.multiskilling')),
                ('skill_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.operatorskill')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refreshment_trainings', to='app1.station')),
            ],
        ),
    ]
