# Generated by Django 5.1.1 on 2025-07-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_trainingreport_unifieddefectreport_multiskilling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineallocation',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='approved', max_length=10),
        ),
    ]
