# Generated by Django 5.2.1 on 2025-07-02 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_connectevent_keyevent_question_voteevent_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.level'),
        ),
        migrations.AddField(
            model_name='score',
            name='skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testsession',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.level'),
        ),
        migrations.AddField(
            model_name='testsession',
            name='skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
