# Generated by Django 5.0.6 on 2025-07-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_score_level_score_skill_testsession_level_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testsession',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='level',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='TestSession',
        ),
    ]
