# Generated by Django 5.0.6 on 2025-07-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_testsession_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='leveltwotraineeinfo',
            name='training_status',
            field=models.CharField(default='No Data', max_length=10),
        ),
    ]
