# Generated by Django 5.0.6 on 2025-07-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_leveltwotraineeinfo_training_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelthreeqatraineeinfo',
            name='training_status',
            field=models.CharField(default='No Data', max_length=10),
        ),
        migrations.AddField(
            model_name='levelthreetraineeinfo',
            name='training_status',
            field=models.CharField(default='No Data', max_length=10),
        ),
        migrations.AddField(
            model_name='leveltwoqatraineeinfo',
            name='training_status',
            field=models.CharField(default='No Data', max_length=10),
        ),
    ]
