# Generated by Django 5.0.6 on 2025-07-03 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_levelthreeqatraineeinfo_training_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testsession',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='level',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='skill',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='TestSession',
        ),
    ]
