# Generated by Django 5.0.6 on 2025-07-03 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_testsession_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='HanContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HanTrainingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('training_file', models.FileField(blank=True, null=True, upload_to='training_files/')),
                ('url_link', models.URLField(blank=True, max_length=500, null=True)),
                ('han_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='app1.hancontent')),
            ],
        ),
        migrations.CreateModel(
            name='ShoTrainingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('training_file', models.FileField(blank=True, null=True, upload_to='training_files/')),
                ('url_link', models.URLField(blank=True, max_length=500, null=True)),
                ('sho_content', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='app1.shocontent')),
            ],
        ),
    ]
