# Generated by Django 5.2.1 on 2025-07-07 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_score_percentage_score_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='score',
            name='test',
        ),
        migrations.AlterField(
            model_name='score',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='percentage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='result',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.station'),
        ),
        migrations.AlterField(
            model_name='score',
            name='test_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
