# Generated by Django 5.2.1 on 2025-07-07 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_remove_score_result_score_passed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.questionpaper'),
        ),
    ]
