# Generated by Django 5.2.3 on 2025-07-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_score_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='arvrtrainingcontent',
            name='url_link',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
