# Generated by Django 4.2.20 on 2025-07-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_arvrtrainingcontent_url_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leveltwotrainingtopic',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
