# Generated by Django 4.2.20 on 2025-07-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_leveltwotrainingtopic_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelthreeqatrainingtopic',
            name='date',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='levelthreetrainingtopic',
            name='date',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='leveltwoqatrainingtopic',
            name='date',
            field=models.CharField(max_length=25),
        ),
    ]
