# Generated by Django 4.2.20 on 2025-07-09 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_levelthreeqatrainingtopic_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MainLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_lines', to='app1.maindepartment')),
            ],
        ),
        migrations.CreateModel(
            name='SubLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('main_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_lines', to='app1.mainline')),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='sub_line',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='app1.subline'),
        ),
    ]
