# Generated by Django 5.0.6 on 2025-07-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_maindepartment_mainline_subline_station_sub_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField()),
                ('new_operators_joined', models.IntegerField()),
                ('new_operators_trained', models.IntegerField()),
                ('total_training_plans', models.IntegerField()),
                ('total_trainings_actual', models.IntegerField()),
                ('total_defects_msil', models.IntegerField()),
                ('ctq_defects_msil', models.IntegerField()),
                ('total_defects_tier1', models.IntegerField()),
                ('ctq_defects_tier1', models.IntegerField()),
                ('total_internal_rejection', models.IntegerField()),
                ('ctq_internal_rejection', models.IntegerField()),
            ],
        ),
    ]
