# Generated by Django 5.0.6 on 2025-07-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_managementreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='machines/'),
        ),
    ]
