# Generated by Django 5.2.4 on 2025-07-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_companylogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylogo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
