# Generated by Django 5.2.4 on 2025-07-11 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_alter_companylogo_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedManpowerCTQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year_ctq', models.DateField(max_length=20)),
                ('total_stations_ctq', models.IntegerField()),
                ('operator_required_ctq', models.IntegerField()),
                ('operator_availability_ctq', models.IntegerField()),
                ('buffer_manpower_required_ctq', models.IntegerField()),
                ('buffer_manpower_availability_ctq', models.IntegerField()),
                ('attrition_trend_ctq', models.IntegerField()),
                ('absentee_trend_ctq', models.IntegerField()),
                ('planned_units_ctq', models.IntegerField()),
                ('actual_production_ctq', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='multiskilling',
            name='skill',
        ),
        migrations.AlterField(
            model_name='multiskilling',
            name='skill_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.level'),
        ),
    ]
