# Generated by Django 5.2.4 on 2025-07-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_advancedmanpowerctq_remove_multiskilling_skill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Any date in the month (used for month tracking)')),
                ('level', models.IntegerField(help_text='Skill level or grade')),
                ('operator_required', models.PositiveIntegerField()),
                ('operator_available', models.PositiveIntegerField()),
            ],
        ),
    ]
