# Generated by Django 5.2.4 on 2025-07-13 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_operatorrequirement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvancedManpowerCTQ',
        ),
        migrations.DeleteModel(
            name='OperatorRequirement',
        ),
    ]
