# Generated by Django 5.2.4 on 2025-07-13 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_delete_advancedmanpowerctq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedManpowerCTQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year_ctq', models.DateField()),
                ('total_stations_ctq', models.IntegerField()),
                ('operator_required_ctq', models.IntegerField()),
                ('operator_availability_ctq', models.IntegerField()),
                ('buffer_manpower_required_ctq', models.IntegerField()),
                ('buffer_manpower_availability_ctq', models.IntegerField()),
                ('attrition_trend_ctq', models.IntegerField()),
                ('absentee_trend_ctq', models.IntegerField()),
                ('planned_units_ctq', models.IntegerField()),
                ('actual_production_ctq', models.IntegerField()),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctq_records', to='app1.department')),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctq_records', to='app1.factory')),
            ],
        ),
        migrations.CreateModel(
            name='OperatorRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Any date in the month (used for month tracking)')),
                ('level', models.IntegerField(help_text='Skill level or grade')),
                ('operator_required', models.PositiveIntegerField()),
                ('operator_available', models.PositiveIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_requirements', to='app1.department')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_requirements', to='app1.factory')),
            ],
        ),
    ]
