# Generated by Django 5.2.4 on 2025-07-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_advancedmanpowerctq_operatorrequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='level',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
