# Generated by Django 5.2.4 on 2025-07-13 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_alter_testsession_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='level',
        ),
        migrations.RemoveField(
            model_name='score',
            name='skill',
        ),
        migrations.AlterField(
            model_name='score',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.testsession'),
        ),
    ]
