# Generated by Django 5.2.4 on 2025-07-13 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_remove_score_level_remove_score_skill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.station'),
        ),
    ]
