# Generated by Django 5.2.4 on 2025-07-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineallocation',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
    ]
