# Generated by Django 5.2.4 on 2025-08-18 05:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_alter_machineallocation_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricattendance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='biometricattendance',
            unique_together={('card_no', 'created_at')},
        ),
    ]
